version: "3.9"

services:
  ui:
    build:
      context: .
    restart: unless-stopped
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
