version: "3.9"

services:
  ui:
    build:
      context: .
      args:
        - NODE_ENV=development
    restart: unless-stopped
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
